kindergarten_project/accounts/api/urls.py
from django.conf.urls import url

from .views import ParentDisplayAPIView

urlpatterns = [
    url(r'^(?P<pk>(\d)+)/parent/$', ParentDisplayAPIView.as_view(), name='detail'),
    url(r'^(?P<pk>(\d)+)/user/$', ParentDisplayAPIView.as_view(), name='detail'),
]

kindergarten_project/accounts/urls.py
from django.conf.urls import url

from .views import ParentDetailView


urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/$', ParentDetailView.as_view(), name='detail'),
]

kindergarten_project/groups/urls.py
from django.conf.urls import url

from .views import (
    ChildDetailView,
    ChildCreateView,
    ChildUpdateView,
    ChildDeleteView,
    GroupDetailView,
    GroupListView,
)

urlpatterns = [
    url(r'^detail/(?P<pk>(\d)+)/$', ChildDetailView.as_view(), name='child-detail'),
    url(r'^update/(?P<pk>(\d)+)/$', ChildUpdateView.as_view(), name='child-update'),
    url(r'^create/$', ChildCreateView.as_view(), name='child-create'),
    url(r'^delete/(?P<pk>(\d)+)/$', ChildDeleteView.as_view(), name='child-delete'),
    url(r'^group-list/$', GroupListView.as_view(), name='group-list'),
    url(r'^(?P<group_name>[\w.@+-]+)/$', GroupDetailView.as_view(), name='group-detail'),

]

kindergarten_project/kindergarten_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from .api_router import router
from main.views import LoginView, SignUpView, MainView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(router.urls)),
    url(r'^profile/', include('accounts.urls', namespace='profile')),
    url(r'^child-group/', include('groups.urls', namespace='child-group')),
    # url(r'^api/profile/', include('accounts.api.urls', namespace='profiles-api')),
    # url(r'^api/groups/', include('groups.api.urls', namespace='groups-api')),
    url(r'^signup/', SignUpView.as_view(), name='signup'),
    url(r'^main/', MainView.as_view(), name='main'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^$', LoginView.as_view(), name='login-view'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kindergarten_project/accounts/models.py
from django.conf import settings
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse_lazy

from groups.models import Child, Group

User = settings.AUTH_USER_MODEL


#Extending User model with two fields

class Parent(models.Model):
    name_of_parent = models.OneToOneField(User)
    # child = models.ManyToManyField(Child, related_name="childs_parent")

    def __str__(self):
        parent_name = self.name_of_parent
        return f"{parent_name}"

    def get_absolute_url(self):
        return reverse_lazy("profile:detail", kwargs={"username": self.name_of_parent})


#Everytime a save event occurs a model is saved
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Parent.objects.create(name_of_parent=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.parent.save()


class Guardian(models.Model):
    user = models.OneToOneField(User, related_name='guardian_profile')
    parent = models.ManyToManyField(Parent, related_name='guardian_parent') # czy potrzebne?
    group = models.ManyToManyField(Group, related_name='group')

    def __str__(self):
        return self.user

kindergarten_project/groups/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.files.storage import FileSystemStorage

User = settings.AUTH_USER_MODEL

fs = FileSystemStorage(location='media')

GROUP = (('Y', 'Younger'),
         ('O','Older'))

ACTIVITIES = (
    ('1', 'Activity_1'),
    ('2', 'Activity_2'),
    ('3', 'Activity_3'),
    ('4', 'Activity_4'),
)

LESSON_UNITS = (
    ('1', 'Unit_1'),
    ('2', 'Unit_2'),
    ('3', 'Unit_3'),
    ('4', 'Unit_4'),
    ('5', 'Unit_5'),
    ('6', 'Unit_6'),
    ('7', 'Unit_7'),
    ('8', 'Unit_8'),
)

DAYS = (
    ('1', 'Monday'),
    ('2', 'Tuesday'),
    ('3', 'Wednesday'),
    ('4', 'Thursday'),
    ('5', 'Friday'),
    ('6', 'Saturday'),
    ('7', 'Sunday'),
)


class Group(models.Model):
    group_name = models.CharField(max_length=255)
    type_of_group = models.CharField(max_length=1, choices=GROUP)
#	child = models.ForeignKey(Child) FK should be in child model so child will be assigned to the group
    #teachers = models.ManyToManyField(Teacher, related_name='teacher_of_group') // trzeba zaimportować z accounts

    def __str__(self):
        return self.group_name


class Child(models.Model):
    name = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='media', blank=True, null=True)
    group = models.ForeignKey(Group, null=True, blank=True)
    parent = models.ForeignKey(User, related_name='parent_of_child')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("child-group:child-detail", kwargs={"pk": self.pk})


class GroupSchedule(models.Model):
    group = models.ForeignKey(Group)
    day = models.IntegerField(choices=DAYS)
    activity = models.IntegerField(choices=ACTIVITIES)
    lesson_unit = models.IntegerField(choices=LESSON_UNITS)

    def __str__(self):
        return 'day: {}, activity: {}'.format(self.day, self.activity)

kindergarten_project/accounts/api/views.py
from django.db.models import Q
from rest_framework import generics
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth import get_user_model

from ..models import Parent
from .serializers import ParentDisplaySerializer, UserDisplaySerializer

User = get_user_model()


class ParentDisplayAPIView(generics.RetrieveUpdateAPIView):
    queryset = Parent.objects.all()
    serializer_class = ParentDisplaySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]



class UserDisplayAPIView(generics.RetrieveUpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserDisplaySerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

kindergarten_project/accounts/views.py
from django.contrib.auth import get_user_model
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, View

from groups.forms import ChildForm
from accounts.models import Parent, Guardian
from groups.models import Child, Group

User = get_user_model()



# class ParentDetailView(DetailView):
#     template_name = 'accounts/parent_detail_view.html'
#     queryset = User.objects.all()
#
#     def get_object(self):
#         username = self.kwargs.get('username')
#         if username is None:
#             raise Http404
#         return get_object_or_404(
#             User,
#             username__iexact=username,
#             # is_active=True
#         )


class ParentDetailView(View):
    def get(self, request, username):
        username = username
        form = ChildForm
        ctx = {
            'form': form,
            'username': username,
        }
        return render(request, 'accounts/parent_detail_view.html', ctx)

#class ParentDetailView(DetailView):
 #   template_name = 'accounts/parent_detail_view.html'
 #   queryset = User.objects.all()

#    def get_object(self):
 #       username = self.kwargs.get('username')
  #         raise Http404
    #    return get_object_or_404(
   #         User,
    #        username__iexact=username,
     #       # is_active=True
      #  )

    # def get_context_data(self, *args, **kwargs):
    #      context = super(ParentDetailView, self).get_context_data(*args, **kwargs)
    #      parent = Parent.objects.get(name_of_parent=self.get_object())
    #      context['children'] = Child.objects.filter(childs_parent=parent)
    #      return context

kindergarten_project/accounts/templates/accounts/parent_detail_view.html
{% extends 'base/base.html' %}

{% block script %}

    <script>

        $(document).ready(function() {
            function clear_field() {
                $('#id_name').val('')
            }

            function ajax_list() {
                var container = $(".container");
                $.ajax({
                    url: "/api/v1/children/",
                    method: "GET",
                    success: function(data){
                        console.log(data);
                    },
                    error: function(data){
                        console.log("error");
                        console.log(data);
                    }
                })
            }

            function form_post_ajax() {
                $(".my-list").submit(function(event) {
                    event.preventDefault();
                    var this_ = $(this);
                    console.log(this_ + "  THIS");
                    var formData = this_.serialize();
                    console.log(formData);
                    $.ajax({
                        type: "POST",
                        url: "/api/v1/children/",
                        data: formData,
                        success: function (data) {
                            console.log('no i co?');
                            console.log(data);
                            clear_field();
                            ajax_list();
                        },
                        error: function (data) {
                            console.log('error');
                            console.log(data.statusText + "  ERROR STATUS TEXT");
                            console.log(data + "  ERROR DATA")

                        }
                    })
                })
            }
            ajax_list();
            form_post_ajax();

        })

    </script>

{% endblock script %}

{% block body %}


    <form class='my-list' action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
    <br/><br/><hr/>
    <div class="container"></div>


{% endblock body %}